### ISSUE TITLE
Direct messages

### ISSUE THREAD

**Issue by rawsp33d** [khyperia/weechat-discord#17]
Is there currently a way to send/receive direct messages and direct group chats through weecord?

**Comment by methanoliver** [comment]
Nothing happens when I receive a direct message, which makes me think there isn't.

That's the one feature I miss sorely.

**Comment by khyperia** [comment]
Direct messages should be supported when receiving a message. I'm not sure why it's not working, I'll see if I can repro.

You are correct in that there's no way to initiate a direct message, however. (To be honest, I had no idea that people other than me and a friend were using this, so I apologize for not checking github issues for quite a long time)

**Comment by khyperia** [comment]
Repro'd, you are correct in that I broke PMs auto-opening when someone messages you. I'll throw up a fix soon.

**Comment by khyperia** [comment]
Whoops, forgot to mention this was partially fixed by ea7ab18f5ac985198ff407ad1a574db27af7e4af . I'll leave this open to track progress on sending of PMs.
