### ISSUE TITLE
error: failed to run custom build command for `weecord v0.1.0

### ISSUE THREAD

**Issue by LovesTha** [khyperia/weechat-discord#20]
After installing the current rust package I get the following error when attempting 'make install'.

Any clues?

/weechat-discord$  [master @ 8800f81] »make install                                                                                                                                                                                               
cargo build --release
    Updating registry `https://github.com/rust-lang/crates.io-index`
    Updating git repository `https://github.com/SpaceManiac/discord-rs.git`
 Downloading libc v0.2.21
 Downloading log v0.3.7
 Downloading websocket v0.17.1
 Downloading byteorder v0.5.3
 Downloading flate2 v0.2.19
 Downloading multipart v0.8.1
 Downloading base64-rs v0.1.1
 Downloading serde_json v0.8.6
 Downloading time v0.1.36
 Downloading hyper v0.9.18
 Downloading bitflags v0.7.0
 Downloading rustc-serialize v0.3.23
 Downloading openssl v0.7.14
 Downloading rand v0.3.15
 Downloading unicase v1.4.0
 Downloading url v1.4.0
 Downloading net2 v0.2.27
 Downloading num_cpus v1.3.0
 Downloading httparse v1.2.1
 Downloading openssl-verify v0.1.0
 Downloading mime v0.2.3
 Downloading solicit v0.4.4
 Downloading traitobject v0.0.1
 Downloading language-tags v0.2.2
 Downloading typeable v0.1.2
 Downloading cookie v0.2.5
 Downloading openssl-sys-extras v0.7.14
 Downloading lazy_static v0.2.8
 Downloading openssl-sys v0.7.17
 Downloading pkg-config v0.3.9
 Downloading gcc v0.3.45
 Downloading hpack v0.2.0
 Downloading idna v0.1.1
 Downloading matches v0.1.4
 Downloading unicode-normalization v0.1.4
 Downloading unicode-bidi v0.2.5
 Downloading rustc_version v0.1.7
 Downloading semver v0.1.20
 Downloading cfg-if v0.1.0
 Downloading miniz-sys v0.1.9
 Downloading mime_guess v1.8.1
 Downloading tempdir v0.3.5
 Downloading phf v0.7.21
 Downloading phf_shared v0.7.21
 Downloading siphasher v0.2.2
 Downloading phf_codegen v0.7.21
 Downloading phf_generator v0.7.21
 Downloading itoa v0.1.1
 Downloading serde v0.8.23
 Downloading dtoa v0.2.2
 Downloading num-traits v0.1.37
   Compiling unicode-normalization v0.1.4
   Compiling base64-rs v0.1.1
   Compiling typeable v0.1.2
   Compiling httparse v1.2.1
   Compiling siphasher v0.2.2
   Compiling traitobject v0.0.1
   Compiling serde v0.8.23
   Compiling matches v0.1.4
   Compiling bitflags v0.7.0
   Compiling gcc v0.3.45
   Compiling language-tags v0.2.2
   Compiling lazy_static v0.2.8
   Compiling libc v0.2.21
   Compiling unicode-bidi v0.2.5
   Compiling rustc-serialize v0.3.23
   Compiling pkg-config v0.3.9
   Compiling semver v0.1.20
   Compiling time v0.1.36
   Compiling openssl-sys v0.7.17
   Compiling idna v0.1.1
   Compiling num-traits v0.1.37
   Compiling cfg-if v0.1.0
   Compiling rand v0.3.15
   Compiling net2 v0.2.27
   Compiling itoa v0.1.1
   Compiling dtoa v0.2.2
   Compiling miniz-sys v0.1.9
   Compiling openssl-sys-extras v0.7.14
   Compiling openssl v0.7.14
   Compiling log v0.3.7
   Compiling weecord v0.1.0 (file:///data/Personal/weechat-discord)
   Compiling byteorder v0.5.3
   Compiling url v1.4.0
   Compiling mime v0.2.3
   Compiling hpack v0.2.0
error: failed to run custom build command for `weecord v0.1.0 (file:///data/Personal/weechat-discord)`
process didn't exit successfully: `/data/Personal/weechat-discord/target/release/build/weecord-35b90ef1118d8d40/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Failure { command: "\"pkg-config\" \"--libs\" \"--cflags\" \"weechat\"", output: Output { status: ExitStatus(ExitStatus(256)), stdout: "", stderr: "Package weechat was not found in the pkg-config search path.\nPerhaps you should add the directory containing `weechat.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'weechat\' found\n" } }', /checkout/src/libcore/result.rs:859
note: Run with `RUST_BACKTRACE=1` for a backtrace.

Build failed, waiting for other jobs to finish...
error: build failed
Makefile:6: recipe for target 'all' failed
make: *** [all] Error 101

**Comment by khyperia** [comment]
It looks like you don't have weechat installed on your system. Make sure weechat is installed and `weechat.pc` is visible to `pkg-config`. Please let me know if that doesn't resolve the issue!

**Comment by LovesTha** [comment]
weechat would be installed, not the dev packages needed for building against it though I suspect :)

Will investigate later.

**Comment by khyperia** [comment]
Seems to have been reported a couple times, and resolved by installing the weechat dev package. Re-open if that's not the case :blush:
