### ISSUE TITLE
Discord API returns channels the user is not in. weechat-discord should filter these out.

### ISSUE THREAD

**Issue by riconnon** [khyperia/weechat-discord#27]
The discord API returns channels the user is not a member of when channels are listed.
See following thread:
https://www.reddit.com/r/discordapp/comments/5mm0qp/bug_windows_phone_discord_users_can_see_channels/

Seems like discord expect clients to implement this filtering.

**Comment by khyperia** [comment]
Should be relatively simple to implement alongside #16. I plan on fixing both issues soon, after the huge refactoring I did this weekend that made a lot of this code way easier to work with (and implement these types of features). Thanks for the report!

**Comment by khyperia** [comment]
Should have been closed by 1bb57f0d640431598da043edb8e89a1ff4f8036b, but I typo'd 21 instead off 27. My bad! This is implemented now :)

**Comment by khyperia** [comment]
Never mind. Apparently this broke stuff. https://github.com/khyperia/weechat-discord/issues/33 is now tracking this issue (I just ripped out the fix for this in https://github.com/khyperia/weechat-discord/commit/b073649ad8b3d723b94e84642d5a77c981a112ca )
