### ISSUE TITLE
License

### ISSUE THREAD

**Issue by nerfingen** [khyperia/weechat-discord#36]
I would like to submit a PKGBUILD to the Arch User Repository, so arch users can build and intsall this plugin in an automated way. But I can't find any licensing information about this software.

(Maybe I'm just blind, that happens from time to time.)

**Comment by khyperia** [comment]
Sorry about that - that's carryover from the "this is just a personal project" phase of development. I threw it under MIT (in that commit just above), which is also what the main dependency ([discord-rs](https://github.com/SpaceManiac/discord-rs)) is under.

But :+1: to putting it on the AUR - I'm also an Arch Linux user, that would be fantastic :). Let me know if there's any packaging issues that I can resolve upstream!

**Comment by nerfingen** [comment]
The package should be online. This is my first AUR package so if you notice that something went wrong, let me know.

**Comment by khyperia** [comment]
Just checked it out, looks fantastic! I might start using it myself :)

Thank you so much for doing that!
